name = "GeoMet"
uuid = "17f98db7-af68-4c95-97fe-c6749748e69a"
authors = ["Geometallurgy Lab - UFMG"]
version = "0.0.1"

[compat]
julia = "1.11"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
